sync-github:
  only:
    refs:
      - master
  stage: sync-github
  before_script: []
  script:
    - git checkout -b master origin/master
    - git remote add github https://gergondet:${GITHUB_TOKEN}@github.com/jrl-umi3218/mc_vrep
    - git push github master:main
  tags:
    - pid, x86_64_linux_abi11

stages:
  - sync-github
