variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libboost-all-dev libgeos++-dev libltdl-dev libmc-rbdyn-urdf-dev libtasks-dev"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/mc_rtc git@gite.lirmm.fr:vrep-utils/vrep-api-wrapper.git"
  CMAKE_ADDITIONAL_OPTIONS: "-DPYTHON_BINDING=OFF"
  MASTER_PPA: "pierre-gergondet+ppa/multi-contact-unstable"
  VREP_URL: "http://coppeliarobotics.com/files/V-REP_PRO_EDU_V3_3_1_64_Linux.tar.gz"
  VREP_ARCHIVE: "V-REP_PRO_EDU_V3_3_1_64_Linux.tar.gz"
  VREP_PATH: "/tmp/V-REP_PRO_EDU_V3_3_1_64_Linux"

before_script:
  - git submodule update --quiet --init --recursive
  - ./.jrl-ci/dependencies/eigen-3.2
  - pushd .
  - cd /tmp
  - wget $VREP_URL
  - tar xzf $VREP_ARCHIVE
  - popd
  - export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DVREP_PATH=${VREP_PATH}"
  - ./.jrl-ci/run before_install

build_gcc:
  stage: build
  script:
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - build
